
GET http://localhost:8001/archers/ HTTP/1.1

###
GET http://localhost:8001/archers/0556f47f-2c65-4af7-ad8c-285aeb465adf HTTP/1.1

###
PUT http://localhost:8001/archers/e842e392-d6a4-4bbe-a54f-acccde959b49/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3ODI2NDgyLCJpYXQiOjE3NDc4MjYxODIsImp0aSI6IjA3NjMwZGVmOGY4NzQzOTk5ZDYwYzQwYjExM2NhZmIyIiwidXNlcl9pZCI6MX0.XNdsbf3WfkRxG_J_u3H2l2GAHKmPIGTgni9W1Ovj_SY

{
    "first_name" : "Harrie",
    "last_name" : "Smulders"
}

###

DELETE http://localhost:8001/archers/e842e392-d6a4-4bbe-a54f-acccde959b49/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3ODI2NDgyLCJpYXQiOjE3NDc4MjYxODIsImp0aSI6IjA3NjMwZGVmOGY4NzQzOTk5ZDYwYzQwYjExM2NhZmIyIiwidXNlcl9pZCI6MX0.XNdsbf3WfkRxG_J_u3H2l2GAHKmPIGTgni9W1Ovj_SY

###

POST http://localhost:8001/archers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3ODI2NDgyLCJpYXQiOjE3NDc4MjYxODIsImp0aSI6IjA3NjMwZGVmOGY4NzQzOTk5ZDYwYzQwYjExM2NhZmIyIiwidXNlcl9pZCI6MX0.XNdsbf3WfkRxG_J_u3H2l2GAHKmPIGTgni9W1Ovj_SY

{
    "first_name" : "Harrie",
    "last_name" : "Smulders"
}

###

POST http://localhost:8001/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

###

POST http://localhost:8001/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzgwNzQ3MywiaWF0IjoxNzQ3NzIxMDczLCJqdGkiOiJkY2EzODE4NTFmMzY0NDBiYTE1MDNjZjMwNmUyYWQ4ZSIsInVzZXJfaWQiOjF9.wPLoai7q-JMcfTGfHS5tC-L7OnvwezcxtoiREkI8an8"
}

###

POST http://localhost:8001/clubs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NDM3MTU0LCJpYXQiOjE3NDg0MzM1NTQsImp0aSI6IjA0M2QxNDE3MTIyZjQ3YTNiOWIyYTM1M2FjM2QzY2M5IiwidXNlcl9pZCI6MX0.U8fUVqq6gDtQKzCi5RcySCFt5z-eQb_P61DpkbNYVDU

{
    "name": "The Newest Amsterdam Archery Club",
    "town": "Amsterdam",
    "info": "A club for archers of all levels.",
    "memberships": [
        {
            "archer": "0a064900-2cd1-4a1a-a880-461188dc2e8b"
        },
        {
            "archer": "91e707a4-3e0d-40f1-87ae-d255a92a94a0"
        },
        {
            "archer": "d4ecd320-c068-4d54-9137-ee5f3fa1c59f"
        }
    ]
}

###

PUT http://localhost:8001/clubs/46b0cf87-1ce7-4e1d-b3fa-647a7f97a868/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NDM3MTU0LCJpYXQiOjE3NDg0MzM1NTQsImp0aSI6IjA0M2QxNDE3MTIyZjQ3YTNiOWIyYTM1M2FjM2QzY2M5IiwidXNlcl9pZCI6MX0.U8fUVqq6gDtQKzCi5RcySCFt5z-eQb_P61DpkbNYVDU

{
    "name": "The More Newest Amsterdam Archery Club",
    "town": "New Amsterdam",
    "info": "A club for archers of all levels.",
    "memberships": [
        {
            "archer": "0a064900-2cd1-4a1a-a880-461188dc2e8b"
        },
        {
            "archer": "91e707a4-3e0d-40f1-87ae-d255a92a94a0"
        },
        {
            "archer": "d4ecd320-c068-4d54-9137-ee5f3fa1c59f"
        }
    ]
}

###

PUT http://localhost:8001/clubs/46b0cf87-1ce7-4e1d-b3fa-647a7f97a868/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NDM3MTU0LCJpYXQiOjE3NDg0MzM1NTQsImp0aSI6IjA0M2QxNDE3MTIyZjQ3YTNiOWIyYTM1M2FjM2QzY2M5IiwidXNlcl9pZCI6MX0.U8fUVqq6gDtQKzCi5RcySCFt5z-eQb_P61DpkbNYVDU

{
    "name": "The More Newest Amsterdam Archery Club",
    "town": "New Amsterdam",
    "info": "A club for archers of all levels.",
    "memberships": []
}

###

DELETE http://localhost:8001/clubs/46b0cf87-1ce7-4e1d-b3fa-647a7f97a868/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NDM3MDA5LCJpYXQiOjE3NDg0MzM0MDksImp0aSI6IjNlOWI0NGY2ZmZlNDQ3ZmI4YmYwZDViZjRkMzAyMjA3IiwidXNlcl9pZCI6MX0.pG4kNLKR_IsAWX-01YS879x38zuWKMGrL8RDcrjjn_M
