# Generated by Django 5.1.1 on 2025-05-30 07:43

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categorymembership_alter_category_archers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymembership',
            name='category',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymemberships', to='api.category', verbose_name='categorymembership category'),
        ),
        migrations.CreateModel(
            name='BowType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='bow type name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='bow type information')),
                ('archer', models.ManyToManyField(blank=True, help_text='format: not required', related_name='bowtypes', to='api.archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowtype_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bow Type',
                'verbose_name_plural': 'Bow Types',
            },
        ),
        migrations.CreateModel(
            name='BowTypeMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowtypemembership_archer', to='api.archer', verbose_name='bowtypemembership archer')),
                ('bowtype', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowtypememberships', to='api.bowtype', verbose_name='bowtypemembership bowtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='contest name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='contest information')),
                ('start_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='start date of contest')),
                ('start_time', models.TimeField(blank=True, help_text='format: H:M:S, not required', null=True, verbose_name='start time of contest')),
                ('archer', models.ManyToManyField(blank=True, help_text='format: not required', related_name='contests', to='api.archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contest_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
        ),
        migrations.CreateModel(
            name='ContestMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='contestmembership_archer', to='api.archer', verbose_name='contestmembership archer')),
                ('contest', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='contestmemberships', to='api.contest', verbose_name='contestmembership contest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='team name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='team information')),
                ('archer', models.ManyToManyField(blank=True, help_text='format: not required', related_name='teams', to='api.archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership_archer', to='api.archer', verbose_name='teammembership archer')),
                ('team', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='teammemberships', to='api.team', verbose_name='teammembership team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
