# Generated by Django 5.1.1 on 2025-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_archer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='address',
            field=models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='address of archer'),
        ),
        migrations.AddField(
            model_name='archer',
            name='city',
            field=models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='city of archer'),
        ),
        migrations.AddField(
            model_name='archer',
            name='email',
            field=models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='email address of archer'),
        ),
        migrations.AddField(
            model_name='archer',
            name='phone',
            field=models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='phone number of archer'),
        ),
        migrations.AddField(
            model_name='archer',
            name='zip_code',
            field=models.CharField(blank=True, help_text='format: not required, max-10', max_length=10, null=True, verbose_name='zip code of archer'),
        ),
    ]
