# Generated by Django 5.1.1 on 2025-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_archer_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowtype',
            name='bow_type',
            field=models.CharField(blank=True, choices=[('recurve', 'Recurve'), ('compound', 'Compound'), ('longbow', 'Longbow'), ('barebow', 'Barebow'), ('crossbow', 'Crossbow'), ('other', 'Other')], help_text='format: not required, max-32', max_length=32, null=True, verbose_name='bow type'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='max_arrow_length',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='maximum arrow length'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='max_draw_weight',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='maximum draw weight'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='min_arrow_length',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='minimum arrow length'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='min_draw_weight',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='minimum draw weight'),
        ),
    ]
