# Generated by Django 5.1.1 on 2025-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_bowtype_max_arrow_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowtype',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('other', 'Other')], help_text='format: not required, max-32', max_length=32, null=True, verbose_name='bow color'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='length',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='bow length in inches'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='material',
            field=models.CharField(blank=True, choices=[('wood', 'Wood'), ('carbon', 'Carbon'), ('aluminum', 'Aluminum'), ('fiberglass', 'Fiberglass'), ('composite', 'Composite'), ('other', 'Other')], help_text='format: not required, max-32', max_length=32, null=True, verbose_name='bow material'),
        ),
    ]
