# Generated by Django 5.1.1 on 2025-06-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bowtype_color_bowtype_length_bowtype_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowtype',
            name='max_draw_length',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='maximum draw length in inches'),
        ),
        migrations.AddField(
            model_name='bowtype',
            name='min_draw_length',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='minimum draw length in inches'),
        ),
    ]
