# Generated by Django 5.1.1 on 2025-06-01 22:24

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bowtype_max_draw_length_bowtype_min_draw_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowString',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='bowstring name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='bowstring information')),
                ('length', models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='bowstring length in inches')),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('other', 'Other')], help_text='format: not required, max-32', max_length=32, null=True, verbose_name='bowstring color')),
                ('material', models.CharField(blank=True, choices=[('dacron', 'Dacron'), ('fastflight', 'FastFlight'), ('other', 'Other')], help_text='format: not required, max-32', max_length=32, null=True, verbose_name='bowstring material')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowstring_author', to=settings.AUTH_USER_MODEL)),
                ('bowtype', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowstrings', to='api.bowtype', verbose_name='bowstring bowtype')),
            ],
            options={
                'verbose_name': 'Bow String',
                'verbose_name_plural': 'Bow Strings',
            },
        ),
    ]
