# Generated by Django 5.1.1 on 2025-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_arrow_bowlimb_bowriser_fletching_arrowfletching'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
        migrations.AddField(
            model_name='archer',
            name='state',
            field=models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='state or province of archer'),
        ),
        migrations.AlterModelTable(
            name='archer',
            table='archer',
        ),
        migrations.AlterModelTable(
            name='club',
            table='club',
        ),
    ]
