# Generated by Django 5.1.1 on 2025-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_club_options_archer_state_alter_archer_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='union_number',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, unique=True, verbose_name='union number of archer'),
        ),
    ]
