# Generated by Django 5.1.1 on 2025-06-03 12:55

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_arrowtype_arrowtypemembership_bestofclub_bowsight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestofclub',
            options={'verbose_name': 'Best of Club', 'verbose_name_plural': 'Best of Clubs'},
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='accessory name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='accessory information')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='AccessoryArcher',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessory', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='accessoryarchers', to='api.accessory', verbose_name='accessoryarcher accessory')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='accessoryarcher_archer', to='api.archer', verbose_name='accessoryarcher archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accessoryarcher_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory Archer',
                'verbose_name_plural': 'Accessory Archers',
            },
        ),
        migrations.CreateModel(
            name='ArcherAccessory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessory', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archeraccessories', to='api.accessory', verbose_name='archeraccessory accessory')),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archeraccessory_archer', to='api.archer', verbose_name='archeraccessory archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='archeraccessory_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archer Accessory',
                'verbose_name_plural': 'Archer Accessories',
            },
        ),
        migrations.CreateModel(
            name='BestOfClubMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bestofclubmembership_archer', to='api.archer', verbose_name='bestofclubmembership archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bestofclubmembership_author', to=settings.AUTH_USER_MODEL)),
                ('bestofclub', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bestofclubmemberships', to='api.bestofclub', verbose_name='bestofclubmembership bestofclub')),
            ],
            options={
                'verbose_name': 'Best of Club Membership',
                'verbose_name_plural': 'Best of Club Memberships',
            },
        ),
    ]
