# Generated by Django 5.1.1 on 2025-06-04 01:27

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_accessoryarcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcherAccessoryMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archeraccessorymembership_archer', to='api.archer', verbose_name='archeraccessorymembership archer')),
                ('archeraccessory', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='archeraccessorymemberships', to='api.archeraccessory', verbose_name='archeraccessorymembership archeraccessory')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='archeraccessorymembership_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archer Accessory Membership',
                'verbose_name_plural': 'Archer Accessory Memberships',
            },
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='bow name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='bow information')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bow_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bow',
                'verbose_name_plural': 'Bows',
            },
        ),
        migrations.CreateModel(
            name='BowMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowmembership_archer', to='api.archer', verbose_name='bowmembership archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowmembership_author', to=settings.AUTH_USER_MODEL)),
                ('bow', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowmemberships', to='api.bow', verbose_name='bowmembership bow')),
            ],
            options={
                'verbose_name': 'Bow Membership',
                'verbose_name_plural': 'Bow Memberships',
            },
        ),
        migrations.CreateModel(
            name='BowSightAccessory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessory', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowsightaccessory_accessory', to='api.accessory', verbose_name='bowsightaccessory accessory')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowsightaccessory_author', to=settings.AUTH_USER_MODEL)),
                ('bowsight', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowsightaccessories', to='api.bowsight', verbose_name='bowsightaccessory bowsight')),
            ],
            options={
                'verbose_name': 'Bow Sight Accessory',
                'verbose_name_plural': 'Bow Sight Accessories',
            },
        ),
        migrations.CreateModel(
            name='BowSightAccessoryMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowsightaccessorymembership_archer', to='api.archer', verbose_name='bowsightaccessorymembership archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowsightaccessorymembership_author', to=settings.AUTH_USER_MODEL)),
                ('bowsightaccessory', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowsightaccessorymemberships', to='api.bowsightaccessory', verbose_name='bowsightaccessorymembership bowsightaccessory')),
            ],
            options={
                'verbose_name': 'Bow Sight Accessory Membership',
                'verbose_name_plural': 'Bow Sight Accessory Memberships',
            },
        ),
    ]
