# Generated by Django 5.1.1 on 2025-06-04 05:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_bowaccessory_archeraccessorymembership_bow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bowaccessory',
            options={'verbose_name': 'Bow Accessory', 'verbose_name_plural': 'Bow Accessories'},
        ),
        migrations.AddField(
            model_name='bowaccessory',
            name='accessory',
            field=models.ForeignKey(default=1, help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowaccessory_accessory', to='api.accessory', verbose_name='bowaccessory accessory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bowaccessory',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowaccessory_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bowaccessory',
            name='bow',
            field=models.ForeignKey(default=1, help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowaccessories', to='api.bow', verbose_name='bowaccessory bow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bowaccessory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BowAccessoryMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowaccessorymembership_archer', to='api.archer', verbose_name='bowaccessorymembership archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowaccessorymembership_author', to=settings.AUTH_USER_MODEL)),
                ('bowaccessory', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowaccessorymemberships', to='api.bowaccessory', verbose_name='bowaccessorymembership bowaccessory')),
            ],
            options={
                'verbose_name': 'Bow Accessory Membership',
                'verbose_name_plural': 'Bow Accessory Memberships',
            },
        ),
        migrations.CreateModel(
            name='BowRiserMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowrisermembership_archer', to='api.archer', verbose_name='bowrisermembership archer')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bowrisermembership_author', to=settings.AUTH_USER_MODEL)),
                ('bowriser', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='bowrisermemberships', to='api.bowriser', verbose_name='bowrisermembership bowriser')),
            ],
            options={
                'verbose_name': 'Bow Riser Membership',
                'verbose_name_plural': 'Bow Riser Memberships',
            },
        ),
    ]
