# Generated by Django 5.1.1 on 2025-06-04 12:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_bowaccessory_options_bowaccessory_accessory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultMembership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='scorememberships', to='api.archer', verbose_name='scoremembership archer')),
                ('score', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='scoremembership_score', to='api.score', verbose_name='scoremembership score')),
            ],
            options={
                'verbose_name': 'Score Membership',
                'verbose_name_plural': 'Score Memberships',
            },
        ),
    ]
