# Generated by Django 5.1.1 on 2025-06-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_resultmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='address of club'),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='email address of club'),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='phone number of club'),
        ),
        migrations.AddField(
            model_name='club',
            name='social_media',
            field=models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='social media handle of club'),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, help_text='format: not required, max-200', null=True, verbose_name='website of club'),
        ),
    ]
