# Generated by Django 5.1.1 on 2025-06-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_club_address_club_email_club_phone_club_social_media_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['start_date'], 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AddField(
            model_name='membership',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='membership_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='info',
            field=models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='membership information'),
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
    ]
