# Generated by Django 5.1.1 on 2025-06-04 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_membership_options_membership_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, foreign key to User model', on_delete=django.db.models.deletion.PROTECT, related_name='archer_author', to=settings.AUTH_USER_MODEL, verbose_name='author of archer'),
        ),
        migrations.AlterField(
            model_name='club',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='clubs', through='api.Membership', to='api.archer', verbose_name='archers in club'),
        ),
    ]
