# Generated by Django 5.1.1 on 2025-06-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_archer_author_alter_club_archers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='age_group',
            field=models.CharField(blank=True, choices=[('youth', 'Youth'), ('junior', 'Junior'), ('senior', 'Senior'), ('master', 'Master'), ('veteran', 'Veteran'), ('other', 'Other')], help_text='format: not required, max-32', max_length=32, null=True, verbose_name='age group of category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='categories', through='api.CategoryMembership', to='api.archer', verbose_name='archers in category'),
        ),
    ]
