# Generated by Django 5.1.1 on 2025-06-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_category_age_group_alter_category_archers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='end date of contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.TimeField(blank=True, help_text='format: H:M:S, not required', null=True, verbose_name='end time of contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='location',
            field=models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='contest location'),
        ),
        migrations.AddField(
            model_name='contest',
            name='scoringsheet',
            field=models.ForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contest_scoringsheet', to='api.scoringsheet', verbose_name='scoringsheet used in contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='targetface',
            field=models.ForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contest_targetface', to='api.targetface', verbose_name='targetface used in contest'),
        ),
        migrations.AlterField(
            model_name='archer',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='archer_author', to=settings.AUTH_USER_MODEL, verbose_name='author of archer'),
        ),
        migrations.AlterField(
            model_name='bowlimb',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowlimb_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bow limb'),
        ),
        migrations.AlterField(
            model_name='bowriser',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowriser_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bow riser'),
        ),
        migrations.AlterField(
            model_name='bowrisermembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowrisermembership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bow riser membership'),
        ),
        migrations.AlterField(
            model_name='bowstring',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowstring_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bow string'),
        ),
        migrations.AlterField(
            model_name='bowtype',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='bowtype_author', to=settings.AUTH_USER_MODEL, verbose_name='author of bow type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='category_author', to=settings.AUTH_USER_MODEL, verbose_name='author of category'),
        ),
        migrations.AlterField(
            model_name='club',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='author_club', to=settings.AUTH_USER_MODEL, verbose_name='author of club'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='contest_author', to=settings.AUTH_USER_MODEL, verbose_name='author of contest'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='membership_author', to=settings.AUTH_USER_MODEL, verbose_name='author of membership'),
        ),
        migrations.AlterField(
            model_name='team',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='team_author', to=settings.AUTH_USER_MODEL, verbose_name='author of team'),
        ),
    ]
