# Generated by Django 5.1.1 on 2025-06-05 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_contest_end_date_contest_end_time_contest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='end date of competition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='end_time',
            field=models.TimeField(blank=True, help_text='format: H:M:S, not required', null=True, verbose_name='end time of competition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='competition location'),
        ),
        migrations.AddField(
            model_name='competition',
            name='scoringsheet',
            field=models.ForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_scoringsheet', to='api.scoringsheet', verbose_name='scoringsheet used in competition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='start date of competition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_time',
            field=models.TimeField(blank=True, help_text='format: H:M:S, not required', null=True, verbose_name='start time of competition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='targetface',
            field=models.ForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_targetface', to='api.targetface', verbose_name='targetface used in competition'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='competition_author', to=settings.AUTH_USER_MODEL, verbose_name='author of competition'),
        ),
        migrations.AlterField(
            model_name='result',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='result_author', to=settings.AUTH_USER_MODEL, verbose_name='author of result'),
        ),
        migrations.AlterField(
            model_name='scoringsheet',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='scoringsheet_author', to=settings.AUTH_USER_MODEL, verbose_name='author of scoring sheet'),
        ),
        migrations.AlterField(
            model_name='targetface',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetface_author', to=settings.AUTH_USER_MODEL, verbose_name='author of target face'),
        ),
    ]
