# Generated by Django 5.1.1 on 2025-05-29 13:28

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_membership_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='category name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='category information')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymember_archer', to='api.archer', verbose_name='archer category member')),
                ('category', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymember_category', to='api.category', verbose_name='category of the archer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='categories', through='api.CategoryMember', to='api.archer'),
        ),
    ]
