# Generated by Django 5.1.1 on 2025-05-29 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_categorymember_category_archers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_archer', to='api.archer', verbose_name='categorymembership archer')),
                ('category', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_category', to='api.category', verbose_name='categorymembership category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='categories', through='api.CategoryMembership', to='api.archer'),
        ),
        migrations.DeleteModel(
            name='CategoryMember',
        ),
    ]
