# Generated by Django 5.1.1 on 2025-05-31 22:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_amount_result_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archer', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='resultmembership_archer', to='api.archer', verbose_name='resultmembership archer')),
                ('result', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='resultmemberships', to='api.result', verbose_name='resultmembership result')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
