# Generated by Django 5.1.1 on 2025-05-31 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_result_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultMembership',
        ),
    ]
