# Generated by Django 5.1.1 on 2025-06-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_archer_created_at_alter_bowtype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='birth_date',
            field=models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='birth date of archer'),
        ),
    ]
