# Generated by Django 5.1.1 on 2025-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_archer_address_archer_city_archer_email_archer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='zip_code',
            field=models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='zip code of archer'),
        ),
    ]
