# Generated by Django 5.1.1 on 2025-06-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_bow_type_bowtype_type_of_bow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowtype',
            name='max_arrow_length',
        ),
        migrations.RemoveField(
            model_name='bowtype',
            name='min_arrow_length',
        ),
    ]
