# Generated by Django 5.1.1 on 2025-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_archer_union_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='info',
            field=models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='archer information'),
        ),
    ]
