# Generated by Django 5.1.1 on 2025-06-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_bestofclub_options_accessory_accessoryarcher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessoryArcher',
        ),
    ]
