
GET http://localhost:8001/archers/ HTTP/1.1

###
GET http://localhost:8001/archers/0556f47f-2c65-4af7-ad8c-285aeb465adf HTTP/1.1

###
PUT http://localhost:8001/archers/e842e392-d6a4-4bbe-a54f-acccde959b49/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3ODI2NDgyLCJpYXQiOjE3NDc4MjYxODIsImp0aSI6IjA3NjMwZGVmOGY4NzQzOTk5ZDYwYzQwYjExM2NhZmIyIiwidXNlcl9pZCI6MX0.XNdsbf3WfkRxG_J_u3H2l2GAHKmPIGTgni9W1Ovj_SY

{
    "first_name" : "Harrie",
    "last_name" : "Smulders"
}

###

DELETE http://localhost:8001/archers/e842e392-d6a4-4bbe-a54f-acccde959b49/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3ODI2NDgyLCJpYXQiOjE3NDc4MjYxODIsImp0aSI6IjA3NjMwZGVmOGY4NzQzOTk5ZDYwYzQwYjExM2NhZmIyIiwidXNlcl9pZCI6MX0.XNdsbf3WfkRxG_J_u3H2l2GAHKmPIGTgni9W1Ovj_SY

###

POST http://localhost:8001/archers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3ODI2NDgyLCJpYXQiOjE3NDc4MjYxODIsImp0aSI6IjA3NjMwZGVmOGY4NzQzOTk5ZDYwYzQwYjExM2NhZmIyIiwidXNlcl9pZCI6MX0.XNdsbf3WfkRxG_J_u3H2l2GAHKmPIGTgni9W1Ovj_SY

{
    "first_name" : "Harrie",
    "last_name" : "Smulders"
}

###

POST http://localhost:8001/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

###

POST http://localhost:8001/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NzgwNzQ3MywiaWF0IjoxNzQ3NzIxMDczLCJqdGkiOiJkY2EzODE4NTFmMzY0NDBiYTE1MDNjZjMwNmUyYWQ4ZSIsInVzZXJfaWQiOjF9.wPLoai7q-JMcfTGfHS5tC-L7OnvwezcxtoiREkI8an8"
}
